### ISSUE TITLE
Roundtrip tests failing?

### ISSUE THREAD

**Issue by avivajpeyi** [avivajpeyi/pywavelet#3]
Hey ollie, we should also take a look at the various tests closely, see why they are failing. 

For example, the LVK SNR seems to not work anymore, and the roundtrip test as well...
See the roundtrip conversion for a simple chirp: 
![chirp](https://github.com/user-attachments/assets/ba806ffb-d00e-4056-87a7-be151d49e4e7)

Large residuals 

See the CI: https://github.com/avivajpeyi/pywavelet/actions/runs/10087911025/job/27892803293#step:6:786

Run locally with:
```
pytest tests
```

**Comment by OllieBurke** [comment]
﻿Hey Avi,This is all fine, I think I know how to fix this. I’ll do this today. We just need to add in a factor of sqrt(2) and potentially delta_t somewhere in the inverse transform. This is to “cancel out” our original changes. The LVK SNR I’ll fiddle around with later as well. OllieOn 25 Jul 2024, at 06:09, Avi Vajpeyi ***@***.***> wrote:﻿
Assigned #3 to @OllieBurke.

**Comment by avivajpeyi** [comment]
@OllieBurke  i think its just that the time->wavelet->time is messed up.

This is time->freq->wavelet->freq (and I compare freq + reconstructed freq). Small errors.
![sine_freq](https://github.com/user-attachments/assets/31b6dd4a-67ef-4ea8-80b1-dd73efe55d90)

This is time->wavelet->time (and I compare time + reconstructed time). Large errors.
![sine_time](https://github.com/user-attachments/assets/f986e157-97c7-4033-b28e-4e09726d5ff2)

**Comment by OllieBurke** [comment]
I believe that the round trip tests are passing now. You should check on your side and once you are happy with this close the issue. On the main branch, this is what is returned when I run the 

`pytest test_roundtrip_conversion.py -s -k test_freqdomain_sine_roundtrip`

command

![sine_freq](https://github.com/user-attachments/assets/80cbf52d-17bb-435a-8ecb-03c4e770ee44)
![sine_time](https://github.com/user-attachments/assets/01bb7c7c-d7a8-4638-b075-17ec7dd7db3c)

**Comment by OllieBurke** [comment]
It all works now and tested for chirping sinusoids. I'm going to close this issue.
