### ISSUE TITLE
Wavelet amplitudes

### ISSUE THREAD

**Issue by avivajpeyi** [avivajpeyi/pywavelet#4]
We're struggling with figuring out what factors of `dt, sqrt(2), etc` are needed to get the wavelet domains to the right amplitudes needed to compute SNRs/LnLs. 

In this issue we'll try to track some notes.

**Comment by avivajpeyi** [comment]
Something to investigate:
- Should the FFT be one-sided? 
- FFT in units of dt or not?

**Comment by OllieBurke** [comment]
I think that this issue can now be closed. 

- The inputs to the wavelet transformation (freq -> wavelet) must have a one-sided transform. 
- FFT must be the default convention of python np.fft.fft and thus have no units if dt, sqrt(2) or anything. Just the raw sum. 
- The SNRs now agree between wavelet/time/frequency domains. 
- The wavelet amplitude for a monochromatic signal (as derived in the overleaf) also agrees with the code. 

I think this is enough to close this issue.
