### ISSUE TITLE
move LISA/LVK studd to case-studies

### ISSUE THREAD

**Issue by avivajpeyi** [avivajpeyi/pywavelet#5]
This repo shouldnt contain LISA/LVK specific code. 
Lets move all of that to https://github.com/pywavelet/case_studies

**Comment by OllieBurke** [comment]
Hey Avi, I've shifted the code (on my local machine) to the case_studies repository and committed my changes. I'm unable to push. Can you give me developer settings or add me as a contributor? Once I can push we can then close this issue.

**Comment by OllieBurke** [comment]
Thanks for adding me as a developer, this will make my life easier. I have moved some stuff over now. How much more do you want to move?

**Comment by OllieBurke** [comment]
Hey Avi, also, can you remove bilby from pywavelet? I don't think it's necessary... keep that for the case studies.
